### ISSUE TITLE
Unexpected API error. KeyError: com.github.brpaz.ulauncher-gitlab

### ISSUE THREAD

**Issue by utrack** [brpaz/ulauncher-gitlab#1]
Hi! This looks like a neat plugin :+1: 
However, I can't get it to work - I receive KeyError w/o any better trace data when trying to auth vs both on-prem gitlab and official gitlab.com.

```
2018-08-22 16:35:48,840 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. KeyError: com.github.brpaz.ulauncher-gitlab
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/site-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 368, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python2.7/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-gitlab'
```

**Comment by brpaz** [comment]
Hi. Please make sure you have installed the "python-gitlab"  package. Missing dependencies is the common cause for this error.

Ex:` pip install python-gitlab`

**Comment by utrack** [comment]
Whoopsie; thank you, that worked.
`pip2 install --user python-gitlab logging re` did the trick.
