### ISSUE TITLE
Dependency confusion / Unexpected API error

### ISSUE THREAD

**Issue by milgner** [brpaz/ulauncher-gitlab#3]
There seem to be two packages: `gitlab` and `python-gitlab` available. Since the README only mentions the latter, I only installed that one. During startup this now prints:

```
Traceback (most recent call last):
  File "/home/marcus/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-gitlab/main.py", line 4, in <module>
    import gitlab
ImportError: No module named gitlab
```

When entering my API token and saving, I get the error messages described in #1:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/site-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 368, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python2.7/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-gitlab'
```

So I tried installing `gitlab`, too. This replaces the error message on startup so it reads

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/api/client/Client.py", line 52, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python2.7/site-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/marcus/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-gitlab/main.py", line 270, in on_event
    extension.gitlab = gitlab.Gitlab(
AttributeError: 'module' object has no attribute 'Gitlab'
```

The same error also occurs when trying to save the access token, so I guess it's safe to say that this module really isn't supposed to be used.
Unfortunately I have no idea how to resolve `ImportError: No module named gitlab` and the `KeyErrror`.

In #1, @utrack suggested that one should also install the `logging` and `re` packages. But when I install `logging`, a lot of errors in the vein of `ImportError: cannot import name NullHandler` start popping up. And the `re` package doesn't seem to exist: `Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/re/`

Any ideas? Btw, your ulauncher plugins really are fantastic - thank you very much for sharing your great work! :tada:

**Comment by brpaz** [comment]
Hello. sorry for the late reply. I think "re" and "logging"  are standard python packages. You shouldn't need to install them.

Regarding the Python GItLab package, make sure you install a version >=1.5.1,<2.0.0

Or I have just updated this extension to the new Ulauncher V5 API and Python 3. You might want to give it a try

**Comment by Innercode** [comment]
Hi,

I digged in to this and fixed it. It's a dependency issue. Whatever I tried, it installed python-gitlab for Python 2.x 
So you have to install `python-pip3` and then `pip3 install --user python-gitlab`

Regards
