### ISSUE TITLE
invalid syntax when running an extension

### ISSUE THREAD

**Issue by utrack** [brpaz/ulauncher-gitlab#6]
```
/usr/lib/python3.7/site-packages/ulauncher/main.py:8: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "/home/u/.local/share:/var/lib/flatpak/exports/share/ulauncher/extensions/com.github.brpaz.ulauncher-gitlab/main.py", line 8, in <module>
    from ulauncher.api.shared.item.ExtensionResultItem import ExtensionResultItem
  File "/usr/lib/python3.7/site-packages/ulauncher/api/shared/item/ExtensionResultItem.py", line 6, in <module>
    from ulauncher.utils.image_loader import load_image
  File "/usr/lib/python3.7/site-packages/ulauncher/utils/image_loader.py", line 10, in <module>
    from ulauncher.config import get_data_file
  File "/usr/lib/python3.7/site-packages/ulauncher/config.py", line 12, in <module>
    from uuid import uuid4
  File "/usr/lib/python3.7/site-packages/uuid.py", line 138
    if not 0 <= time_low < 1<<32L:
                                ^
SyntaxError: invalid syntax
```

**Comment by brpaz** [comment]
This error seems not to be related to the extension itself but with a package "uuid", that Ulauncher depends on it. I guess it might be related to some Python version mismatch. or having an older version of the `uuid` package installed

You might try to update the `uuid` package on your system with `pip install uuid`. - see https://github.com/bigchaindb/bigchaindb/issues/1848 for a similar problem.

I will close this. If you still have this problem please open this issue on [Ulauncher](https://github.com/Ulauncher) github repository.
