### ISSUE TITLE
UnhandledError

### ISSUE THREAD

**Issue by inputsh** [brpaz/ulauncher-gitlab#7]
How I triggered it:

* Changed the keyword from `glab` to `git`
* Changed the URL to the self-hosted instance.
* Entered my token (with `api` scope).

End result:

```
Message: 'com.github.brpaz.ulauncher-gitlab'
Error Name: UnhandledError
Type: KeyError

Stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 417, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-gitlab'

```

I've tried switching a field or two and I always seem to trigger this stacktrace. I've tried leaving the keyword to `glab`, as well as using GitLab.com access token instead of my own instance.

**Comment by akuzia** [comment]
same error in ulauncher v5.4.0 on Manjaro
Message: 'com.github.brpaz.ulauncher-gitlab'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 417, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-gitlab'

```

**Comment by AtjonTV** [comment]
I just had the same error and fixed it by going into the extension folder and running make:

```bash
$ cd ~/.local/share/ulauncher/extensions/com.github.brpaz.ulauncher-gitlab
$ make deps
```

(This simply runns the PIP command to install the Python-Gitlab dependency)

**Comment by brpaz** [comment]
Yes. This error usually means a missing dependency. What @AtjonTV said should work. I will close this for now.
